### ISSUE TITLE
Broken RPM dependency for rhel7.http24-php55 

### ISSUE THREAD

**Issue by VojtechVitek** [sclorg/rhscl-dockerfiles#1]
```
cd rhel7.httpd24-php55
docker build -t rhel7.http24-php55 .
```

https://github.com/sclorg/rhscl-dockerfiles/blob/2bbd4bce34c28887ccb1acfbdd41c55f6e383210/rhel7.httpd24-php55/Dockerfile#L7

```
...
---> Package policycoreutils-python.x86_64 0:2.2.5-11.el7_0.1 will be installed
--> Processing Dependency: libcgroup for package: policycoreutils-python-2.2.5-11.el7_0.1.x86_64
--> Finished Dependency Resolution
Error: Package: policycoreutils-python-2.2.5-11.el7_0.1.x86_64 (oso-rhui-rhel-server-releases)
           Requires: libcgroup
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

UPDATE: The issue is caused by both `httpd24` and `php55` RPMs.

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
