### ISSUE TITLE
the referred devtoolset-4 repos are missing

### ISSUE THREAD

**Issue by lfarkas** [sclorg/rhscl-dockerfiles#16]
hi,
repos like
https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/
is missing and there is no such directory at all.
or we just have to wait for it?

**Comment by hhorak** [comment]
It's not available yet, we'll try to have it available soon. Please, be patient.

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
