### ISSUE TITLE
rhel6.httpd24-php55 (and similar) should enable two SCLs instead of one

### ISSUE THREAD

**Issue by VojtechVitek** [sclorg/rhscl-dockerfiles#2]
[rhel6.httpd24-php55](https://github.com/sclorg/rhscl-dockerfiles/tree/master/rhel6.httpd24-php55) currently enables `httpd24` SCL only (see its [enablehttpd24.sh](https://github.com/sclorg/rhscl-dockerfiles/blob/master/rhel6.httpd24-php55/enablehttpd24.sh)).

But it should enable both `httpd24` and `php55` SCLs.

This issue applies to the other double-SCLs as well.

UPDATE: Applies to both RHEL6 and RHEL7.

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
