### ISSUE TITLE
RoR images should include ImageMagick libs

### ISSUE THREAD

**Issue by jhadvig** [sclorg/rhscl-dockerfiles#25]
RoR images should include ImageMagick libs:
`ImageMagick ImageMagick-devel`
since they need if for installing `rmagick` gem, cause most of the Rails applications(Spree, Redmine, etc..) are using it.
maybe Ruby images as well.

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
