### ISSUE TITLE
Suspected Bug in assemble script: BUNDLE_WITHOUT is ignored

### ISSUE THREAD

**Issue by severinraez** [sclorg/rhscl-dockerfiles#26]
Hi

**Problem**

The _BUNDLE_WITHOUT_ variable in https://github.com/sclorg/rhscl-dockerfiles/blob/master/centos7.rh-ruby22/s2i/bin/assemble is set, but never exported. This leads to bundler installing development dependencies when building the container for use in production. This in turn fails if e.g. capybara is a dev dependency:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/rh/rh-ruby22/root/usr/bin/ruby -r ./siteconf20160928-25-1bsiulc.rb extconf.rb 
*** extconf.rb failed ***
```

**Proposed fix**

Adding 

```
    export BUNDLE_WITHOUT=$BUNDLE_WITHOUT
```

on line 36 of the assemble script fixes the issue.

**Workaround**

A workaround for this is to declare _ENV BUNDLE_WITHOUT=development:test_ in your application Dockerfile before calling the assemble script.

Cheers,
Severin

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
