### ISSUE TITLE
Compatibility problems with the new BitBucket Pipelines service

### ISSUE THREAD

**Issue by ncoghlan** [sclorg/rhscl-dockerfiles#27]
BitBucket Pipelines is a new service from Atlassian that lets you integrate CI and deployment pipelines directly into BitBucket: https://confluence.atlassian.com/bitbucket/bitbucket-pipelines-792496469.html

The main interface to this is a YAML file that lets you specify a base container image, and then a series of commands to run in that image. Unfortunately, the command they use to run the build container appears to break the automatic activation of the SCL:

```
+ docker run -t --rm=true --cidfile=/tmp/1477283280612-0/{c7c2d4f1-41ad-4bcf-9eb3-505c630ffc1f} --entrypoint=/bin/bash --memory=4096m --env-file=/tmp/dockerEnvironment8830083261622265345.env -v /tmp/bashScript3894533593351410934.sh:/tmp/bashScript3894533593351410934.sh:ro -v build-volume-fae92e8c-9c3e-48e8-9435-27c7ba3a1e4b:/opt/atlassian/pipelines:rw -v build-volume-fae92e8c-9c3e-48e8-9435-27c7ba3a1e4b:/opt/atlassian/bitbucketci:rw -w /opt/atlassian/pipelines/agent/build --label com.atlassian.pipelines.agent="dadc25681ad9" "centos/python-35-centos7" -i /tmp/bashScript3894533593351410934.sh
```

A simpler command run locally does the right thing:

```
$ echo "which python && which pip" > check_pip.sh
$ docker run --rm -it --entrypoint=/bin/bash -v `pwd`:/tmp/hostpwd:z centos/python-35-centos7 /tmp/hostpwd/check_pip.sh
/opt/rh/rh-python35/root/usr/bin/python
/opt/rh/rh-python35/root/usr/bin/pip
```

So I'm guessing the problem may be with BitBucket's usage of the `--env-file` option.

I tried adding `source scl_source enable rh-python35` to the build commands, but that failed on the `source` command itself.

**Comment by ncoghlan** [comment]
History of my experiments trying to get this to work before switching to using Fedora 24 instead: https://bitbucket.org/ncoghlan/curiousefficiency/history-node/680ec732a406/bitbucket-pipelines.yml?at=default

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
