### ISSUE TITLE
Upgrade RHSC postgres to 9.6

### ISSUE THREAD

**Issue by jayunit100** [sclorg/rhscl-dockerfiles#29]
We'd love to have a tracking issue for 9.6 postgres.  Other postgres images expect to run as "postgres" user (or maybe as root), so this is important for openshift deployments.

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
