### ISSUE TITLE
Don't include shebang for scl source scripts

### ISSUE THREAD

**Issue by mnagy** [sclorg/rhscl-dockerfiles#6]
E.g.:
https://github.com/sclorg/rhscl-dockerfiles/blob/master/rhel6.ruby200/enableruby200.sh#L1

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.
